version: '3'
services:
  queue:
    # Lists Reddit comments and sends relevant ones to the workers.
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    # command: python -m src
    volumes:
      - ./src:/home/bot/src:delegated
    environment:
      JOB_TIMEOUT: 3600
      REDIS_HOST: redis
  worker:
    # Receives jobs and does the recording work.
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    # command: rq worker --with-scheduler --quiet --url redis://redis
    environment:
      JOB_TIMEOUT: 1800
      LOG_DIR: /tmp/logs
      REDIS_HOST: redis
    volumes:
      - ${PWD}/logs:/tmp/logs
      - ./src:/home/bot/src:delegated
  redis:
    # Job queue backend and persistent storage service.
    image: redis:6
    restart: unless-stopped
    command: --appendonly yes --loglevel warning
    volumes:
      - ${PWD}/data:/data
