version: '3'
services:
  image:
    build: .
    image: osr2mp4-bot
    command: 'true'
  reddit:
    # Lists Reddit comments and sends relevant ones to the workers.
    image: osr2mp4-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - image
      - redis
    command: python -m src.reddit
    environment:
      JOB_TIMEOUT: 1800
      REDIS_HOST: redis
  discord:
    # Receives jobs from Discord messages.
    image: osr2mp4-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - image
      - redis
    command: python -m src.discord
    environment:
      JOB_TIMEOUT: 1800
      REDIS_HOST: redis
      SHARE_DIR: /tmp/share
    volumes:
      - share:/tmp/share
  worker:
    # Receives jobs and does the recording work.
    image: osr2mp4-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - files
      - image
      - redis
    command: rq worker --with-scheduler --quiet --url redis://redis reddit discord default
    environment:
      JOB_TIMEOUT: 1800
      REDIS_HOST: redis
      SHARE_DIR: /tmp/share
    volumes:
      - share:/tmp/share
  files:
    # Publically accessible file server where Streamable can read videos from.
    image: halverneus/static-file-server:v1.8.1
    restart: unless-stopped
    environment:
      FOLDER: /data
      PORT: 8080
    volumes:
      - share:/data
    ports:
      - ${SERVER_PORT:-80}:8080
  redis:
    # Job queue backend and persistent storage service.
    image: redis:6
    restart: unless-stopped
    command: --appendonly yes --loglevel warning
    volumes:
      - ${PWD}/data:/data
volumes:
  share:
