version: '3'
services:
  queue:
    # Lists Reddit comments and sends relevant ones to the workers.
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: python -m src
    environment:
      JOB_TIMEOUT: 3600
      REDIS_HOST: redis
  worker:
    # Receives jobs and does the recording work.
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - files
      - redis
    command: rq worker --with-scheduler --quiet --url redis://redis
    environment:
      JOB_TIMEOUT: 3600
      LOG_DIR: /tmp/logs
      REDIS_HOST: redis
      VIDEO_DIR: /tmp/videos
    volumes:
      - ${PWD}/logs:/tmp/logs
      - videos:/tmp/videos
  files:
    # Publically accessible file server where Streamable can read videos from.
    image: halverneus/static-file-server:v1.8.1
    restart: unless-stopped
    environment:
      FOLDER: /data
      PORT: 8080
    volumes:
      - videos:/data
    ports:
      - ${SERVER_PORT:-80}:8080
  redis:
    # Job queue backend and persistent storage service.
    image: redis:6
    restart: unless-stopped
    command: --appendonly yes --loglevel warning
    volumes:
      - ${PWD}/data:/data
volumes:
  videos:
