version: '3'
services:
  queue:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: python -m bot
    environment:
      JOB_TIMEOUT: 900
      REDIS_HOST: redis
  worker:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: rq worker --with-scheduler --quiet --url redis://redis
    environment:
      JOB_TIMEOUT: 900
      LOG_DIR: /tmp/logs
      REDIS_HOST: redis
      SELENIUM_HOST: selenium
      VIDEO_DIR: /tmp/videos
    volumes:
      - ${PWD}/logs:/tmp/logs
      - videos:/tmp/videos
  files:
    image: halverneus/static-file-server:v1.8.1
    restart: unless-stopped
    environment:
      FOLDER: /data
      PORT: 8080
    volumes:
      - videos:/data
    ports:
      - 80:8080
  redis:
    image: redis:6
    restart: unless-stopped
    command: --appendonly yes --loglevel warning
    volumes:
      - ${PWD}/data:/data
  selenium:
    image: selenium/standalone-firefox:3.141.59-20201010
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
    logging:
      driver: none
volumes:
  videos:
