version: '3'
services:
  server:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: python -m bot
    environment:
      REDIS_HOST: redis
  worker:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: rq worker -q -u redis://redis
    environment:
      LOG_DIR: /tmp/logs
    volumes:
      - ${PWD}/logs:/tmp/logs
  redis:
    image: redis:6
    restart: unless-stopped
