version: '3'
services:
  queue:
    # Lists Reddit comments and sends relevant ones to the workers.
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: python -m bot
    environment:
      JOB_TIMEOUT: 1800
      REDIS_HOST: redis
  worker:
    # Receives jobs and does the recording work.
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - files
      - redis
      - selenium
    command: rq worker --with-scheduler --quiet --url redis://redis
    environment:
      JOB_TIMEOUT: 1800
      LOG_DIR: /tmp/logs
      REDIS_HOST: redis
      SELENIUM_HOST: selenium
      VIDEO_DIR: /tmp/videos
    volumes:
      - ${PWD}/logs:/tmp/logs
      - videos:/tmp/videos
  files:
    # Publically accessible file server where Streamable can read videos from.
    image: halverneus/static-file-server:v1.8.1
    restart: unless-stopped
    environment:
      FOLDER: /data
      PORT: 8080
    volumes:
      - videos:/data
    ports:
      - 80:8080
  redis:
    # Job queue backend and persistent storage service.
    image: redis:6
    restart: unless-stopped
    command: --appendonly yes --loglevel warning
    volumes:
      - ${PWD}/data:/data
  selenium:
    # Required for initiating Streamable uploads.
    image: selenium/standalone-firefox:3.141.59-20201010
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
    logging:
      driver: none
volumes:
  videos:
